#Bedroom Lamp One Button Remote
sensor:
  - name: "Remote Lamp Battery"
    unique_id: bedroom_lamp_remote_battery
    state_topic: "bedroom/lamp/remote"
    unit_of_measurement: "v"
    value_template: "{{ value_json.batt }}"

  - name: "Remote Lamp Power"
    unique_id: bedroom_lamp_remote_pwr
    state_topic: "bedroom/lamp/remote"
    value_template: "{{ value_json.pwr }}"
